Language support for Modelica
o2sh/onefetch pull request #1262
Opened 2024-01-24 06:53 UTC by dietmarw

## Purpose
Adding language support and icon art for [Modelica](https://modelica.org).

## Logo Reference

![m_ball](https://github.com/o2sh/onefetch/assets/9332/6852fee4-5ab3-45fe-ac87-7c651e78fdc0)

2024-01-24 13:24 UTC, spenserblack requested changes
Merging this won't be possible right now because our current tool for language detection [doesn't support Modelica](https://github.com/XAMPPRocky/tokei/blob/5f755db185937b33f38a30e7f6facfa5be0f146a/languages.json). We'd need tokei to support Modelica, and also have a new release featuring that support.

That's the most significant blocking issue currently, though we may [eventually switch tools for language detection](https://github.com/o2sh/onefetch/pull/1152).

2024-01-24 13:24 UTC, spenserblack commented on languages.yaml
> +    {0}            ######       #####      #####
Looks like some of these lines are a bit too wide. [We enforce a 40-character maximum width at compile time](https://github.com/o2sh/onefetch/actions/runs/7636714914/job/20804507063?pr=1262#step:5:632).

2024-01-24 14:57 UTC, dietmarw commented
I noticed the missing tokei support too and have now submitted a PR for that: https://github.com/XAMPPRocky/tokei/pull/1061

2024-01-24 17:26 UTC, dietmarw commented
@spenserblack Regarding #1152 , is there anything I could already do wrt adding Modelica in case that is resolved before 
https://github.com/XAMPPRocky/tokei/pull/1061 ?

2024-01-24 18:55 UTC, spenserblack commented
Yeah you can make an issue or PR into https://github.com/spenserblack/gengo if you want. What's most important is knowledge, not code, so an issue is sufficient, but PRs are very welcome!
I can't say when we'll switch over from tokei to gengo, but I'm pretty confident that we can at least deploy new languages more rapidly (and also resolve language ambiguity) when we do.

2024-01-24 19:09 UTC, spenserblack commented on languages.yaml
> +    {0}                          {1}***
```suggestion
    {0}      #######     ########    #########
    {0}    ########### ########################
    {0}  #######  ###########  ########### ####
    {0}######      #######     ########   #####
    {0}#####      ######      #######    #####
    {0}###      ######       ######     #####
    {0}        ######       #####      #####
    {0}      #####       ######       ###
    {0}      #####       ######
    {0}    #####        ####     {1}***
    {0}  #####          ##     {1}*******
    {0} #####                 {1}*********
    {0}####                   {1}*********
    {0}##                      {1}*******
    {0}                          {1}***
```

2024-01-24 19:17 UTC, spenserblack approved these changes
Alright, contribution LGTM. The only thing that's left is us resolving upstream issues, so I'm approving this.

2024-08-16 11:13 UTC, dietmarw commented
Upstream has just merged the addition: https://github.com/XAMPPRocky/tokei/pull/1061

2024-08-16 12:06 UTC, spenserblack commented
We'll need to wait for the next release.

2024-12-29 17:57 UTC, o2sh approved these changes
Thanks a lot for your contribution @dietmarw 🎉 

I took the liberty to clean the ASCII logo slightly https://vercel-gjf16v1xk-o2shs-projects.vercel.app/#Modelica

The PR should be ready to be merged

2024-12-29 18:04 UTC, merged

2025-01-05 15:41 UTC, dietmarw commented
> Thanks a lot for your contribution @dietmarw 🎉
> 
> I took the liberty to clean the ASCII logo slightly https://vercel-gjf16v1xk-o2shs-projects.vercel.app/#Modelica
> 
> The PR should be ready to be merged

Thanks @o2sh :-)