Language Support for ATS
o2sh/onefetch pull request #523
Opened 2021-10-27 09:06 UTC by pykenny

## Purpose
Adding language support and icon art for [ATS](http://www.ats-lang.org/).

Language support at `tokei` is still undergoing review, and will provide screenshot once it's available.

## Logo Reference
http://www.ats-lang.org/MYDATA/theLogo.png

## Preview
|view|
| - |
|<img src="https://user-images.githubusercontent.com/6328813/139037127-35360e25-c0ff-4134-b324-e13dbb96f399.png" width="300"></img>|

## Related PR/issues:
 - #490
 - XAMPPRocky/tokei#840

2022-02-18 16:27 UTC, spenserblack commented
I wonder when there will be a new release of tokei. https://github.com/XAMPPRocky/tokei/pull/840 was merged a long time ago.

2022-02-19 20:31 UTC, o2sh commented
Yeah, tokei's last [release](https://github.com/XAMPPRocky/tokei/releases/tag/v12.1.2) is more than year old 😟

2022-05-22 00:02 UTC, o2sh commented
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

2022-12-19 03:33 UTC, spenserblack requested changes

2022-12-19 03:33 UTC, spenserblack commented on languages.yaml
> +    chip: #1AC620
```suggestion
      - '#FFFF00'
      - '#FF0000'
      - '#0000FF'
    chip: '#1AC620'
```

2022-12-19 03:42 UTC, spenserblack approved these changes

2023-09-01 19:25 UTC, spenserblack commented
Wow, every day I find a new pending PR :laughing:

@pykenny FYI: #1152

2023-09-09 02:18 UTC, pykenny commented
@spenserblack Sorry for not noticing conflict with upstream. Try the CI pipeline again?

2023-09-09 02:35 UTC, spenserblack commented
@pykenny no worries. Although the CI will likely still fail right now since tokei hasn't been released with support for ATS yet. Though hopefully gengo will fix that :wink:

Anyway, I don't think you have to worry about this PR. You've done all that we could ask a contributor to do to add a new language. it just depends on us fixing upstream issues.

2024-06-09 08:45 UTC, pykenny commented
There's some major update on onefetch, so redo the commit from current main branch for simplicity.

2024-06-10 11:59 UTC, spenserblack requested changes

2024-06-10 11:59 UTC, spenserblack commented on languages.yaml
> +  serialization: ATS
```suggestion
```
Our serialization is typically lowercase. This populates the available options for the `--ascii-language` option. You don't really need to use this option unless you're adding special characters (`CSharp` -> `c#`) or renaming (`Sh` -> `shell`).

2024-12-29 18:15 UTC, merged