Create WinGet workflow
o2sh/onefetch pull request #673
Opened 2022-05-26 18:16 UTC by russellbanks

This pull request adds a workflow that automatically publishes Onefetch to WinGet every release. *Please do not merge this pull request without reading the below and making the required changes* (The token part is the important bit) :)

- `runs-on: windows-latest`

The WinGet Releaser action can only run on Windows.

</br>

- `identifier: o2sh.onefetch`

This is the identifier for Onefetch on Winget. It will use this to find Onefetch's current package on WinGet.

</br>

- `installers-regex: '\.exe$'`

This will make all `.exe` files in the assets of the latest Onefetch release to be included in the pull request.

</br>

- `delete-previous-version: 'true'`

This is optional, and you are welcome to change this to false (or omit it; the default is false). This will essentially overwrite the previous version on WinGet packages, so that only this new version is stored on WinGet. Again, entirely optional.

</br>

- `token: ${{ secrets.WINGET_TOKEN }}`

This is the bit that will require action from yourself. This is a GitHub token with which the action will authenticate with GitHub and create a pull request on the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository.

To do this, you will need to:

1. Create a Personal Access Token (PAT) with `public_repo` scope on your GitHub account.
![image](https://user-images.githubusercontent.com/74878137/170548538-0d689177-5c9e-4bb2-8a87-e09eb5ca64e8.png)

2. Create a repository secret containing the token. **Super important: call this token: `WINGET_TOKEN`**.
See [using encrypted secrets in a workflow](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) for more details.

</br>

**Finally, make sure you have a fork of [winget-pkgs](https://github.com/microsoft/winget-pkgs) on your GitHub account. Please do not delete the fork after a pull request has been merged as the action will use that fork for making a branch and merging it with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every Onefetch release.**

The above is made on the assumption that the account that the token is from (and the fork is present) is @o2sh. If you would like this to be done by another account, a few changes would have to be made to this pull request.

If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro) and the source code is [here](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/releaser-action/action.yml).

2022-05-26 19:14 UTC, spenserblack requested changes
:thinking: It would probably be ideal if this could be combined with the `CD` workflow. Then you can [set that this job needs `deploy`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds), which seems necessary as it looks like this action relies on assets already being published. Probably better than just retrying every 10 minutes up to the 5th try. It's also ideal for this job to simply not run if the `deploy` job fails.

******

You can ignore my note on `uses: vedantmgoyal20009/...`. I'm not requesting a change there, just making a note.

2022-05-26 19:16 UTC, spenserblack commented
>The WinGet Releaser action can only run on Windows.

It could be made into a [docker action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) to allow it to run on ubuntu/macos, but then it wouldn't be able to run on windows :laughing: :upside_down_face: 
(though the docker image itself could run Windows AFAIK)

2022-05-26 19:19 UTC, russellbanks commented
> 🤔 It would probably be ideal if this could be combined with the `CD` workflow. Then you can [set that this job needs `deploy`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds), which seems necessary as it looks like this action relies on assets already being published. Probably better than just retrying every 10 minutes up to the 5th try. It's also ideal for this job to simply not run if the `deploy` job fails.

I actually made an issue about a similar thing I had: [#442](https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/442), asking for it to be allowed to be ran on other workflow events. However, they [said they ran into an issue with this](https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/442#issuecomment-1122096742):

> @russellbanks I was testing the action with the `workflow_run` event, but the problem is the action won't be able to get the release information automatically as it does now and my main concern while creating the action was only that a user would not have to supply everything as an input for the action.

2022-05-26 19:19 UTC, spenserblack commented
Huh, just took a quick look, but it seems like this could honestly be automated with [`winget-create`](https://github.com/microsoft/winget-create), which also supports submitting PRs.

2022-05-26 19:21 UTC, spenserblack commented
> I actually made an issue about a similar issue I had: [#442](https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/442), asking for it to be allowed to be ran on other workflow events.

With the `needs:` option a job can be delayed until another job is finished, and still be triggered with `on: release` by being part of the same overall workflow.

2022-05-26 19:28 UTC, russellbanks commented
> With the needs: option a job can be delayed until another job is finished, and still be triggered with on: release by being part of the same overall workflow.

I didn't consider this. Thank you :)

> Huh, just took a quick look, but it seems like this could honestly be automated with [winget-create](https://github.com/microsoft/winget-create), which also supports submitting PRs.

I imagine this reason that this hasn't be done already is because wingetcreate isn't as verbose in its options as the script is maybe? For example, being able to delete a previous version.

</br>

Meanwhile, I could tag always vedantmgoyal2009 for visibility on this? I imagine they'd be happy to help

2022-05-29 18:42 UTC, spenserblack commented
AFAIK there wouldn't be any problem changing the action trigger type to `released`, but we should get confirmation from @o2sh since they've been creating the releases so far, and see if they care about the timing. Although wouldn't all needed event attributes (assets, tag, publish date, etc.) be available with the `published` release type, too?

2022-05-29 19:52 UTC, o2sh commented
TBH, I've just learned - thanks to @vedantmgoyal2009 comment - the distinction between the `published`  and the `released` trigger type 😅.  I agree with @vedantmgoyal2009, the CD pipeline should only be triggered on release --> ac338c8

2022-05-29 20:20 UTC, o2sh commented
@russellbanks I created the token:
<img width="823" alt="Screenshot 2022-05-29 at 22 18 48" src="https://user-images.githubusercontent.com/13710835/170889847-d9340ab0-98ce-4aa3-acf5-f506d4c45e69.png">

2022-05-29 20:22 UTC, russellbanks commented
> @russellbanks I created the token

Brill, just make sure you've added that token to this repository and then this can be merged :)

2022-05-29 20:36 UTC, o2sh commented
done:

<img width="802" alt="Screenshot 2022-05-29 at 22 23 49" src="https://user-images.githubusercontent.com/13710835/170890368-9909d361-66ce-4cbd-92b8-85eaeeaf52a4.png">

I'll let @spenserblack finish his review and approve the PR, did you settle on [this](https://github.com/o2sh/onefetch/pull/673#pullrequestreview-986643860)?

2022-05-29 21:58 UTC, spenserblack commented
Thanks for the changes, @o2sh! With this, we should be able to add this as a job to the CD workflow, so that it only triggers after a release is created. Something vaguely like this
```yaml
jobs:
  deploy:
    # ...
  winget-pkg-release:
    needs: [deploy]
    runs-on: windows-latest
    # etc.
```

******

BTW, a `max-retries` input `winget-pkgs-automation/releaser-action` might be cool. In our specific case, as long as we have guaranteed that `deploy` has completed before this action, then it would probably fail as soon as possibly instead of retrying. This is because, if there are no assets available after `deploy` is finished, something has gone *really* wrong and another try wouldn't really help.

2022-05-29 22:14 UTC, spenserblack commented
Oh, also I just thought about this:
@vedantmgoyal2009 currently your action requires a special token instead of the built-in `GITHUB_TOKEN` because the action uses another repository to generate a PR. But you could actually clone `winget-pkgs` into the same repo and generate a PR from there, thus allowing you to use `GITHUB_TOKEN`. Here's an example of what that would look like:

```bash
git remote add winget https://github.com/microsoft/winget-pkgs.git
git fetch winget
git branch winget-pkg winget/master
git checkout winget-pkg
# make changes
git push -u origin winget-pkg
# make PR from <repo>:winget-pkg to microsoft/winget-pkgs:master
```

It's not blocking this PR, but it's a way to make your action more friendly to users 🙂

2022-05-30 15:22 UTC, russellbanks commented
I've made those changes

2022-05-30 16:33 UTC, spenserblack approved these changes
LGTM!

2022-05-30 19:14 UTC, merged