adding language ABNF
o2sh/onefetch pull request #811
Opened 2022-10-08 01:06 UTC by atluft

The image for this is inspired by the railroad diagram that are used with syntax diagrams that ABNF usually represent.

I couldn't find a color for chip on the linguist site.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/2379260/194679927-6a9c4e0c-80d0-482f-ae6a-a054d2e4f096.png">

2022-10-08 10:47 UTC, o2sh commented on languages.yaml
> +    {0}>>--+-->| /--\ |-->+--->>
```suggestion
    {0}>>---+-->| /--\ |-->+--->>
```

2022-10-08 19:46 UTC, spenserblack requested changes
Thank you!
I personally like how this looks on a dark terminal, but I think the majority prefer more contrast. Especially since this logo has many "thin" characters. It's a bit hard to see in the [preview](https://vercel-nrp91cpgc-o2sh.vercel.app/).
`#888888` is about the halfway point between completely light (`#FFFFFF`) and completely dark `#000000`.

2022-10-08 19:46 UTC, spenserblack commented on languages.yaml
> +      - '#555555'
```suggestion
      - '#888888'
```

2022-10-08 20:43 UTC, o2sh commented on languages.yaml
> +    {0}        |______|
```suggestion
    {0}          ______
    {0}         |      |
    {0}         |  /\  |
    {0}>>---+-->| /--\ |-->+--->>
    {0}     |   |______|   |
    {0}     |    ______    |
    {0}     |   |  __  |   |
    {0}     |   | |__) |   |
    {0}     +-->| |__) |-->+
    {0}     |   |______|   |
    {0}     |    ______    |
    {0}     |   |      |   |
    {0}     |   | |\ | |   |
    {0}     +-->| | \| |-->+
    {0}     |   |______|   |
    {0}     |    ______    |
    {0}     |   |  ___ |   |
    {0}     |   | |___ |   |
    {0}     +-->| |    |-->+
    {0}         |______| 
```
I suggest increasing the width of letters `B` and `F` to match the other letters.

![image](https://user-images.githubusercontent.com/13710835/194727171-f78ed9b9-3b4e-4bb7-9df4-baf24d130be7.png)

2022-10-09 17:22 UTC, atluft commented
Hi @o2sh and @spenserblack,
Thank you, agree those changes make ABNF look better.

2022-10-09 18:32 UTC, merged